/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_besar.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import tugas_besar.controller.IuranController;
import tugas_besar.database.IuranConnection;
import tugas_besar.database.IuranDatabase;
import tugas_besar.entity.Iuran;
import tugas_besar.error.IuranException;
import tugas_besar.event.IuranListener;
import tugas_besar.model.IuranModel;
import tugas_besar.model.TabelIuranModel;
import tugas_besar.service.IuranDao;

/**
 *
 * @author yustitia arofa
 */
public class IuranView extends javax.swing.JPanel implements IuranListener, ListSelectionListener {

    /**
     * Creates new form IuranView
     */
    private final TabelIuranModel Tmodel;
    private final IuranModel Imodel;
    private final IuranController controller;
    public DefaultTableModel tabelmodel;
    
   

    public IuranView() {
        Tmodel = new TabelIuranModel();
        Imodel =  new IuranModel();
        
        controller = new IuranController();
        
        
        initComponents();
        
       Imodel.setListener(this);
       controller.setModel(Imodel);
        
        TabelIuran.getSelectionModel().addListSelectionListener(this);
        TabelIuran.setModel(Tmodel);

    }

    public JComboBox<String> getBlnBox() {
        return BlnBox;
    }

    public JTable getTabelIuran() {
        return TabelIuran;
    }

    public JComboBox<String> getStatusBox() {
        return statusBox;
    }

    public JTextField getTxtAlamat() {
        return txtAlamat;
    }

    public JTextField getTxtRT() {
        return txtRT;
    }

    public JTextField getTxtSerch() {
        return txtSerch;
    }

    public JTextField getTxtnamaKK() {
        return txtnamaKK;
    }

    public JTextField getTxtnoKK() {
        return txtnoKK;
    }

    public JTextField getTxttahun() {
        return txttahun;
    }

    public JTextField getTxttgl() {
        return txttgl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Btn_simpan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Btn_Hapus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Btn_ubah = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Btn_reset = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Btn_keluar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        masukaPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSerch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnoKK = new javax.swing.JTextField();
        txtnamaKK = new javax.swing.JTextField();
        txtRT = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txttgl = new javax.swing.JTextField();
        BlnBox = new javax.swing.JComboBox<>();
        txttahun = new javax.swing.JTextField();
        statusBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelIuran = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contPanel.setBackground(new java.awt.Color(153, 153, 153));
        contPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Iuran");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/monitor.png"))); // NOI18N

        Btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        Btn_simpan.setText("SIMPAN");
        Btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_simpanMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N

        Btn_Hapus.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Btn_Hapus.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Hapus.setText("HAPUS");
        Btn_Hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_HapusMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N

        Btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ubah.setText("UBAH");
        Btn_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_ubahMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/recycling.png"))); // NOI18N

        Btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        Btn_reset.setText("RESET");
        Btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_resetMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N

        Btn_keluar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_keluar.setText("KELUAR");
        Btn_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_keluarMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N

        javax.swing.GroupLayout contPanelLayout = new javax.swing.GroupLayout(contPanel);
        contPanel.setLayout(contPanelLayout);
        contPanelLayout.setHorizontalGroup(
            contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(contPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(contPanelLayout.createSequentialGroup()
                .addGroup(contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3))
                    .addGroup(contPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_reset))
                    .addGroup(contPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        contPanelLayout.setVerticalGroup(
            contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(Btn_simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(Btn_Hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(Btn_ubah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(Btn_reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Btn_keluar))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        add(contPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 470));

        masukaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 51, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Halo Admin");

        txtSerch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerchKeyReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/musica-searcher.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("No kartu keluarga  ");

        jLabel9.setText("Nama kepala keluarga ");

        jLabel10.setText("Alamat ");

        jLabel11.setText("tanggal/bulan/tahun ");

        jLabel12.setText(" RT");

        jLabel13.setText("status");

        txtnoKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoKKActionPerformed(evt);
            }
        });

        txtnamaKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaKKActionPerformed(evt);
            }
        });

        txttgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttglActionPerformed(evt);
            }
        });

        BlnBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Febuari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));

        statusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUDAH", "BELUM" }));

        TabelIuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelIuran);

        javax.swing.GroupLayout masukaPanelLayout = new javax.swing.GroupLayout(masukaPanel);
        masukaPanel.setLayout(masukaPanelLayout);
        masukaPanelLayout.setHorizontalGroup(
            masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukaPanelLayout.createSequentialGroup()
                .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masukaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masukaPanelLayout.createSequentialGroup()
                        .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(51, 51, 51)
                        .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamaKK, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(masukaPanelLayout.createSequentialGroup()
                                .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BlnBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnoKK, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        masukaPanelLayout.setVerticalGroup(
            masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukaPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnoKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtnamaKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(masukaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(masukaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 590, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void txtnoKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoKKActionPerformed

    private void txttglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttglActionPerformed

    private void txtnamaKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaKKActionPerformed

    private void Btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_simpanMouseClicked
        // TODO add your handling code here:
        controller.InsetIuran(this);
    }//GEN-LAST:event_Btn_simpanMouseClicked

    private void Btn_HapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_HapusMouseClicked
        // TODO add your handling code here:
        controller.DeleteIuran(this);
    }//GEN-LAST:event_Btn_HapusMouseClicked

    private void Btn_ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ubahMouseClicked
        // TODO add your handling code here:
        controller.UpdateIuran(this);
    }//GEN-LAST:event_Btn_ubahMouseClicked

    private void Btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_resetMouseClicked
        // TODO add your handling code here:
        controller.resetIuran(this);
    }//GEN-LAST:event_Btn_resetMouseClicked

    private void Btn_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_keluarMouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Ingin Keluar?","Perhatian",dialogBtn);
        if (dialogResult == 0){
            System.exit(0);
        }else{
            
        }
        
    }//GEN-LAST:event_Btn_keluarMouseClicked

    private void txtSerchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerchKeyReleased
        // TODO add your handling code here:
        tabelmodel = new DefaultTableModel();
        TabelIuran.setModel(tabelmodel);
        tabelmodel.addColumn("NO_KK");
        tabelmodel.addColumn("NAMA_KK");
        tabelmodel.addColumn("RT");
        tabelmodel.addColumn("ALAMAT");
        tabelmodel.addColumn("TANGGAL");
        tabelmodel.addColumn("BULAN");
        tabelmodel.addColumn("TAHUN");
        tabelmodel.addColumn("STATUS");
        
        try {
            Connection konek = new IuranConnection().getConnection();
            Statement st = konek.createStatement();
            String sql = "SELECT*FROM IURAN WHERE NO_KK LIKE '%"+txtSerch.getText()+"%'"+"OR NAMA_KK LIKE'%"+txtSerch.getText()+"%'";
            ResultSet r = st.executeQuery(sql);
            while (r.next()) {
             tabelmodel.addRow(new Object[]{
             r.getString(1),
             r.getString(2),
             r.getString(3),
             r.getString(4),
             r.getString(5),
             r.getString(6),
             r.getString(7),
             r.getString(8)
             });            
             }TabelIuran.setModel(tabelmodel);
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_txtSerchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BlnBox;
    private javax.swing.JLabel Btn_Hapus;
    private javax.swing.JLabel Btn_keluar;
    private javax.swing.JLabel Btn_reset;
    private javax.swing.JLabel Btn_simpan;
    private javax.swing.JLabel Btn_ubah;
    private javax.swing.JTable TabelIuran;
    private javax.swing.JPanel contPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel masukaPanel;
    private javax.swing.JComboBox<String> statusBox;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtRT;
    private javax.swing.JTextField txtSerch;
    private javax.swing.JTextField txtnamaKK;
    private javax.swing.JTextField txtnoKK;
    private javax.swing.JTextField txttahun;
    private javax.swing.JTextField txttgl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(IuranModel model) {

        txtnoKK.setText(model.getNo_kk());
        txtnamaKK.setText(model.getNama_kk());
        txtRT.setText(model.getRt());
        txtAlamat.setText(model.getAlamat());
        txttgl.setText(model.getTanggal());
        BlnBox.setToolTipText(model.getBulan());
        txttahun.setText(model.getTahun());
        statusBox.setToolTipText(model.getStatus());
    }

    @Override
    public void onInsert(Iuran iuran) {
        Tmodel.add(iuran);
    }

    @Override
    public void onDelete() {
        int index = TabelIuran.getSelectedRow();
        Tmodel.remove(index);

    }

    @Override
    public void onUpdate(Iuran iuran) {

        int index = TabelIuran.getSelectedRow();
        Tmodel.set(index, iuran);

    }

    @Override
    public void valueChanged(ListSelectionEvent lse) {

        try {
            Iuran model = Tmodel.get(TabelIuran.getSelectedRow());
            txtnoKK.setText(model.getNo_kk());
            txtnamaKK.setText(model.getNama_kk());
            txtRT.setText(model.getRt());
            txtAlamat.setText(model.getAlamat());
            txttgl.setText(model.getTanggal());
            BlnBox.setToolTipText(model.getBulan());
            txttahun.setText(model.getTahun());
            statusBox.setToolTipText(model.getStatus());
        } catch (IndexOutOfBoundsException ex) {
        }
    }
    public void LoadDatabase()throws SQLException, IuranException{
        IuranDao dao = IuranDatabase.getIuranDao();
        Tmodel.setList(dao.selectAllIuran());
    
    }
}
