/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_besar.view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tugas_besar.database.IuranConnection;

/**
 *
 * @author yustitia arofa
 */
public class WargaTampil extends javax.swing.JPanel {

    /**
     * Creates new form WargaTampil
     */
    public DefaultTableModel tabelmodel;
    

    public WargaTampil() {

        initComponents();
        tabelmodel = new DefaultTableModel();
        TabelIuran3.setModel(tabelmodel);
        tabelmodel.addColumn("NO_KK");
        tabelmodel.addColumn("NAMA_KK");
        tabelmodel.addColumn("RT");
        tabelmodel.addColumn("ALAMAT");
        tabelmodel.addColumn("TANGGAL");
        tabelmodel.addColumn("BULAN");
        tabelmodel.addColumn("TAHUN");
        tabelmodel.addColumn("STATUS");
        
       
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kontrol_panel1 = new javax.swing.JPanel();
        btn_news = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_data = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        status1 = new javax.swing.JPanel();
        Panel_berita = new javax.swing.JPanel();
        PanelAwal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_awal = new javax.swing.JButton();
        PanelPindah = new javax.swing.JPanel();
        panelOpen = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pabelBerita = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        panelTabel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelIuran3 = new javax.swing.JTable();
        SerchUser = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kontrol_panel1.setBackground(new java.awt.Color(255, 204, 0));
        kontrol_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_news.setBackground(new java.awt.Color(255, 204, 0));
        btn_news.setToolTipText("");
        btn_news.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_newsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_newsMouseReleased(evt);
            }
        });
        btn_news.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                btn_newsInputMethodTextChanged(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/newspaper(1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_newsLayout = new javax.swing.GroupLayout(btn_news);
        btn_news.setLayout(btn_newsLayout);
        btn_newsLayout.setHorizontalGroup(
            btn_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_newsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_newsLayout.setVerticalGroup(
            btn_newsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_newsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        kontrol_panel1.add(btn_news, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 40, 40));

        Btn_data.setBackground(new java.awt.Color(255, 204, 0));
        Btn_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_dataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_dataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_dataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Btn_dataMouseReleased(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder(1).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Btn_dataLayout = new javax.swing.GroupLayout(Btn_data);
        Btn_data.setLayout(Btn_dataLayout);
        Btn_dataLayout.setHorizontalGroup(
            Btn_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Btn_dataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        Btn_dataLayout.setVerticalGroup(
            Btn_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Btn_dataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        kontrol_panel1.add(Btn_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 40, 40));

        btn_logout.setBackground(new java.awt.Color(255, 204, 0));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_logoutMouseReleased(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/power-circle-and-line-symbol(1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_logoutLayout = new javax.swing.GroupLayout(btn_logout);
        btn_logout.setLayout(btn_logoutLayout);
        btn_logoutLayout.setHorizontalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_logoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        btn_logoutLayout.setVerticalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_logoutLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        kontrol_panel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 40, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/monitor.png"))); // NOI18N
        kontrol_panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 8)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data");
        kontrol_panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 153));
        jLabel9.setText("Iuran");
        kontrol_panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 10));
        kontrol_panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 40, 10));

        jPanel1.add(kontrol_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 640));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(960, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 20));

        status1.setLayout(new java.awt.CardLayout());

        Panel_berita.setBackground(new java.awt.Color(102, 102, 102));
        Panel_berita.setForeground(new java.awt.Color(102, 102, 102));

        PanelAwal.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204,50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tk kircon.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Pembangunan TK");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Berita");

        btn_awal.setBackground(new java.awt.Color(102, 102, 102));
        btn_awal.setText("Panel Awal");
        btn_awal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_awalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAwalLayout = new javax.swing.GroupLayout(PanelAwal);
        PanelAwal.setLayout(PanelAwalLayout);
        PanelAwalLayout.setHorizontalGroup(
            PanelAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAwalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAwalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_awal)
                .addContainerGap())
        );
        PanelAwalLayout.setVerticalGroup(
            PanelAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_awal)
                .addGap(28, 28, 28))
        );

        PanelPindah.setLayout(new java.awt.CardLayout());

        panelOpen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("\"Membaca tanpa merenungkan adalah bagaikan makan");
        panelOpen.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 380, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Budayakanlah Membaca");
        panelOpen.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 290, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("-Adisri");
        panelOpen.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("tanpa dicerna\"");
        panelOpen.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bandung-2.jpg"))); // NOI18N
        panelOpen.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 492, 580));

        PanelPindah.add(panelOpen, "card3");

        pabelBerita.setBackground(new java.awt.Color(204, 204, 204));
        pabelBerita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(" Fokus pelaksanaan kegiatan pembangunan ini adalah pada pemben\nahan/perbaikan fasilitas bangunan di lingkungan TK Budi Utami \nGlugo, yang dipergunakan sebagai tempat pelaksanaan kegiatan \nPAUD “KENANGA” Pedukuhan Glugo.\n Kegiatan ini adalah dengan merenovasi Gudang milik TK Budi \nUtamiGlugo sehingga menjadi sebuah ruangan yang dapat diperg-\nunakan untuk pembelajaran secara “indoor” bagi pelaksanaan PAUD\n“KENANGA” Pedukuhan Glugo, yang dilaksanakan pada tanggal 29De-\nsember 2012 – 07 Februari 2013.\nHasil Kegiatan Pembangunan : Berupa ruangan untuk kegiatan PAUD\n“KENANGA” Pedukuhan Glugo yang representatif dengan ukuran 4 x\n10 m2 yang berdiri di bagian belakang dari TK Budi Utami Glugo.\nDiharapkan dari hasil pembangunan ruangan ini, maka kegiatan be-\nlajar-mengajar dari “KENANGA” Pedukuhan Glugo  dapat berjalan le\nbih baik dan lebih lancar. Data selengkapnya dapat dilihat pada Foto \nDokumentasi Kegiatan terlampir.\n Kegiatan pembangunan ini menghabiskan dana sejumlah Rp.11.192.250,-\n (sebelas juta seratus sembilan puluh dua ribu dua ratus lima puluh \nrupiah). Adapun bantuan dari Pemdes Panggungharjo sejumlah Rp. 7.500.000,\n- dan Kas TK Budi Utami Rp.  1.372.250,-; kas PAUD KENANGA Rp.  1.000.000,- \nserta bantuan/partisipasi dari masyarakat yang berupa barang langsung sejumlah \nRp.  1.320.000,-.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tk kircon.jpg"))); // NOI18N

        javax.swing.GroupLayout pabelBeritaLayout = new javax.swing.GroupLayout(pabelBerita);
        pabelBerita.setLayout(pabelBeritaLayout);
        pabelBeritaLayout.setHorizontalGroup(
            pabelBeritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pabelBeritaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pabelBeritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pabelBeritaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pabelBeritaLayout.setVerticalGroup(
            pabelBeritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pabelBeritaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        PanelPindah.add(pabelBerita, "card2");

        javax.swing.GroupLayout Panel_beritaLayout = new javax.swing.GroupLayout(Panel_berita);
        Panel_berita.setLayout(Panel_beritaLayout);
        Panel_beritaLayout.setHorizontalGroup(
            Panel_beritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_beritaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelPindah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        Panel_beritaLayout.setVerticalGroup(
            Panel_beritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_beritaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_beritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPindah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        status1.add(Panel_berita, "card3");

        panelTabel.setBackground(new java.awt.Color(102, 102, 102));

        TabelIuran3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TabelIuran3);

        SerchUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SerchUserKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("@Copyright Kelompok 8");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/musica-searcher.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Halo warga ");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Silahkan cari nama anda di laman pencarian yang sudah kami sediakan");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nama_KK = Nama Kepala Keluarga");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NO_KK = Nomer Kartu Keluarga");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("keterangan :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(26, 26, 26)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTabelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(SerchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SerchUser))
                    .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        status1.add(panelTabel, "card3");

        jPanel1.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 940, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btn_newsInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_newsInputMethodTextChanged

    private void btn_newsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newsMouseClicked
        // TODO add your handling code here:
        //panel remove
        status1.removeAll();
        status1.repaint();
        status1.revalidate();
        //panel
        status1.add(Panel_berita);
        status1.repaint();
        status1.revalidate();
    }//GEN-LAST:event_btn_newsMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //panel remove
        status1.removeAll();
        status1.repaint();
        status1.revalidate();
        //panel
        status1.add(Panel_berita);
        status1.repaint();
        status1.revalidate();

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //panel remove
        status1.removeAll();
        status1.repaint();
        status1.revalidate();
        //panel
        status1.add(panelTabel);
        status1.repaint();
        status1.revalidate();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void Btn_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dataMouseClicked
        // TODO add your handling code here:
        //panel remove
        status1.removeAll();
        status1.repaint();
        status1.revalidate();
        //panel
        status1.add(panelTabel);
        status1.repaint();
        status1.revalidate();
    }//GEN-LAST:event_Btn_dataMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Ingin Keluar?", "Perhatian", dialogBtn);
        if (dialogResult == 0) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Ingin Keluar?", "Perhatian", dialogBtn);
        if (dialogResult == 0) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_newsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newsMouseEntered
        // TODO add your handling code here:
        btn_news.setBackground(new Color(153, 0, 102));

    }//GEN-LAST:event_btn_newsMouseEntered

    private void btn_newsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newsMouseExited
        // TODO add your handling code here:
        btn_news.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_btn_newsMouseExited

    private void btn_newsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newsMousePressed
        // TODO add your handling code here:
        btn_news.setBackground(new Color(102, 0, 102));
    }//GEN-LAST:event_btn_newsMousePressed

    private void btn_newsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newsMouseReleased
        // TODO add your handling code here:
        btn_news.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_btn_newsMouseReleased

    private void Btn_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dataMouseEntered
        // TODO add your handling code here:
        Btn_data.setBackground(new Color(153, 0, 102));

    }//GEN-LAST:event_Btn_dataMouseEntered

    private void Btn_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dataMouseExited
        // TODO add your handling code here:
        Btn_data.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_Btn_dataMouseExited

    private void Btn_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dataMousePressed
        // TODO add your handling code here:
        Btn_data.setBackground(new Color(102, 0, 102));
    }//GEN-LAST:event_Btn_dataMousePressed

    private void Btn_dataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dataMouseReleased
        // TODO add your handling code here:
        Btn_data.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_Btn_dataMouseReleased

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
        btn_logout.setBackground(new Color(250, 0, 0));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        btn_logout.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseReleased
        // TODO add your handling code here
        btn_logout.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_btn_logoutMouseReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        //panell remove
        PanelPindah.removeAll();
        PanelPindah.repaint();
        PanelPindah.revalidate();
        //panel add
        PanelPindah.add(pabelBerita);
        PanelPindah.repaint();
        PanelPindah.revalidate();

    }//GEN-LAST:event_jLabel5MouseClicked

    private void btn_awalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_awalActionPerformed
        // TODO add your handling code here:
        //panell remove
        PanelPindah.removeAll();
        PanelPindah.repaint();
        PanelPindah.revalidate();
        //panel add
        PanelPindah.add(panelOpen);
        PanelPindah.repaint();
        PanelPindah.revalidate();

    }//GEN-LAST:event_btn_awalActionPerformed

    private void SerchUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SerchUserKeyReleased
        // TODO add your handling code here:
        tabelmodel = new DefaultTableModel();
        TabelIuran3.setModel(tabelmodel);
        tabelmodel.addColumn("NO_KK");
        tabelmodel.addColumn("NAMA_KK");
        tabelmodel.addColumn("RT");
        tabelmodel.addColumn("ALAMAT");
        tabelmodel.addColumn("TANGGAL");
        tabelmodel.addColumn("BULAN");
        tabelmodel.addColumn("TAHUN");
        tabelmodel.addColumn("STATUS");
        
         try {
            Connection konek = new IuranConnection().getConnection();
            Statement st = konek.createStatement();
            String sql = "SELECT*FROM IURAN WHERE NO_KK LIKE '%"+SerchUser.getText()+"%'"+"OR NAMA_KK LIKE'%"+SerchUser.getText()+"%'";
            ResultSet r = st.executeQuery(sql);
             while (r.next()) {
             tabelmodel.addRow(new Object[]{
             r.getString(1),
             r.getString(2),
             r.getString(3),
             r.getString(4),
             r.getString(5),
             r.getString(6),
             r.getString(7),
             r.getString(8)
             });            
             }TabelIuran3.setModel(tabelmodel);
          
        } catch (SQLException e) {
        }

    }//GEN-LAST:event_SerchUserKeyReleased
    public void getData() {
        tabelmodel.getDataVector().removeAllElements();
        tabelmodel.fireTableDataChanged();
        try {
            Connection konek = new IuranConnection().getConnection();
            Statement statement = konek.createStatement();
            String sql = "SELECT*FROM IURAN";
            ResultSet r = statement.executeQuery(sql);
            while (r.next()) {
                Object[] o = new Object[8];
                o[0] = r.getString("NO_KK");
                o[1] = r.getString("NAMA_KK");
                o[2] = r.getString("RT");
                o[3] = r.getString("ALAMAT");
                o[4] = r.getString("TANGGAL");
                o[5] = r.getString("BULAN");
                o[6] = r.getString("TAHUN");
                o[7] = r.getString("STATUS");
                tabelmodel.addRow(o);
            }
        } catch (SQLException e) {

        }

    }

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Btn_data;
    private javax.swing.JPanel PanelAwal;
    private javax.swing.JPanel PanelPindah;
    private javax.swing.JPanel Panel_berita;
    private javax.swing.JTextField SerchUser;
    private javax.swing.JTable TabelIuran3;
    private javax.swing.JButton btn_awal;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_news;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel kontrol_panel1;
    private javax.swing.JPanel pabelBerita;
    private javax.swing.JPanel panelOpen;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JPanel status1;
    // End of variables declaration//GEN-END:variables

}
